import '@polymer/app-route/app-location';
import '@polymer/app-route/app-route';
import '@polymer/iron-flex-layout/iron-flex-layout.js';
import '@polymer/app-layout/app-scroll-effects/app-scroll-effects.js';
import '@polymer/app-layout/app-header-layout/app-header-layout'
import '@polymer/app-layout/app-header/app-header'
import '@polymer/app-layout/app-toolbar/app-toolbar'
import '@polymer/iron-icon/iron-icon';
import '@polymer/iron-form/iron-form';
import '@polymer/iron-icons/av-icons';
import '@polymer/iron-icons/editor-icons';
import '@polymer/iron-icons/hardware-icons';
import '@polymer/iron-icons/image-icons';
import '@polymer/iron-icons/iron-icons';
import '@polymer/iron-icons/maps-icons';
import '@polymer/iron-icons/social-icons';
import '@polymer/iron-pages/iron-pages';
import '@polymer/iron-selector/iron-selector';
import '@polymer/paper-styles/paper-styles'
import '@polymer/paper-button/paper-button';
import '@polymer/paper-icon-button/paper-icon-button';
import '@polymer/paper-tabs/paper-tab';
import '@polymer/paper-tabs/paper-tabs';
import '@polymer/paper-dropdown-menu/paper-dropdown-menu';
import '@polymer/paper-fab/paper-fab.js';
import '@polymer/app-layout/app-scroll-effects/effects/waterfall.js';
import '@polymer/app-layout/app-box/app-box.js';
import '@polymer/paper-card/paper-card.js';
